sudo: required
services:
    - docker

before_install:
    - docker build -t stefanociceri/docker-react -f Dockerfile.dev .
    
script:
    - docker run stefanociceri/docker-react npm run test -- --coverage