sudo: required
services:
    - docker

before_install:
    - docker build -t stefanociceri/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true stefanociceri/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "Docker-React"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-227616062713"
    bucket_path: "Docker-React"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY